#!/usr/bin/env bash
# Run meerail-agent in the background on macOS, via a launchd LaunchAgent.
#
# Generates ~/Library/LaunchAgents/de.meerail.agent.plist with this checkout's
# real paths baked in, then bootstraps it into your GUI session so the agent
# starts at login and is restarted if it dies.
#
# It must be a LaunchAgent, not a LaunchDaemon: Proton Bridge runs inside your
# logged-in GUI session and only listens on loopback, so a daemon starting at
# boot would have nothing to connect to.
set -euo pipefail
cd "$(dirname "$0")"

LABEL="de.meerail.agent"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG="$HOME/Library/Logs/meerail-agent.log"
AGENT_DIR="$(pwd)"
DOMAIN="gui/$(id -u)"

if [ "$(uname -s)" != "Darwin" ]; then
  echo "service.sh is macOS-only (launchd). On Linux use 'make agent-docker' or" >&2
  echo "the systemd user unit in README.md; on Windows, Task Scheduler." >&2
  exit 1
fi

usage() {
  cat <<'USAGE'
Run meerail-agent in the background, as a launchd LaunchAgent (macOS only).

  ./service.sh install     write the plist, load it, start syncing
  ./service.sh status      loaded? running? what did it exit with?
  ./service.sh logs        tail the log
  ./service.sh restart     bounce it (after editing config.toml)
  ./service.sh stop        stop + unload, but keep the plist
  ./service.sh start       load it again after a stop
  ./service.sh uninstall   stop, unload, delete the plist

  --config PATH            run the agent against a config other than
                           agent/config.toml (install only)
USAGE
}

# XML-escape a path before interpolating it into the plist.
xml_escape() { printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'; }

write_plist() {
  local config_arg="" run_sh="$AGENT_DIR/run.sh"

  if [ -n "${CONFIG_PATH:-}" ]; then
    # Resolve now: launchd starts the job from WorkingDirectory, so a relative
    # path here would be resolved against the wrong directory at login.
    local resolved
    resolved="$(cd "$(dirname "$CONFIG_PATH")" && pwd)/$(basename "$CONFIG_PATH")"
    config_arg="
        <string>--config</string>
        <string>$(xml_escape "$resolved")</string>"
  fi

  mkdir -p "$(dirname "$PLIST")" "$(dirname "$LOG")"
  cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by agent/service.sh — re-run 'service.sh install' to regenerate. -->
<plist version="1.0">
<dict>
    <key>Label</key>            <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$(xml_escape "$run_sh")</string>$config_arg
    </array>
    <key>WorkingDirectory</key> <string>$(xml_escape "$AGENT_DIR")</string>
    <key>RunAtLoad</key>        <true/>
    <!-- Restart on any exit. The agent is stateless — its cursors live in
         Postgres — so a restart just resumes where it left off. -->
    <key>KeepAlive</key>        <true/>
    <!-- Bridge opens its IMAP port before it has loaded accounts, so an agent
         that wins the race at login gets 'no such user'. 30s between respawns
         keeps that from becoming a hot loop while Bridge finishes starting. -->
    <key>ThrottleInterval</key> <integer>30</integer>
    <!-- launchd hands jobs a minimal PATH; run.sh needs python3 to build the
         venv, which is often Homebrew's rather than /usr/bin's. -->
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key> <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <!-- No ProcessType: the default (Standard) is deliberate. 'Background'
         would let the system throttle CPU and I/O, which is exactly wrong for
         the multi-GB first sync. -->
    <key>StandardOutPath</key>  <string>$(xml_escape "$LOG")</string>
    <key>StandardErrorPath</key><string>$(xml_escape "$LOG")</string>
</dict>
</plist>
PLIST_EOF
}

# bootout is a no-op-with-an-error when the job isn't loaded; callers decide
# whether that matters, so swallow it here.
unload() { launchctl bootout "$DOMAIN/$LABEL" 2>/dev/null || true; }

load() { launchctl bootstrap "$DOMAIN" "$PLIST"; }

require_plist() {
  if [ ! -f "$PLIST" ]; then
    echo "Not installed — no $PLIST. Run: ./service.sh install" >&2
    exit 1
  fi
}

cmd_install() {
  if [ ! -f config.toml ] && [ -z "${CONFIG_PATH:-}" ]; then
    echo "No config.toml here. Copy config.example.toml and fill it in first:" >&2
    echo "  cp config.example.toml config.toml && chmod 600 config.toml" >&2
    exit 1
  fi
  if [ ! -d .venv ]; then
    # run.sh would build it on first launch, but doing it here means a failure
    # surfaces on your terminal rather than as a 30s launchd respawn loop.
    echo "No .venv yet — building it, and checking your connections."
    ./run.sh --test
  fi

  write_plist
  # Reload rather than fail if it is already loaded, so install doubles as
  # "pick up my edits to this script".
  unload
  load
  echo "Installed and started: $LABEL"
  echo "  plist   $PLIST"
  echo "  log     $LOG"
  echo "  status  ./service.sh status"
}

cmd_uninstall() {
  unload
  rm -f "$PLIST"
  echo "Uninstalled $LABEL. The log at $LOG was left in place."
}

cmd_start() { require_plist; load; echo "Started $LABEL."; }
cmd_stop() { require_plist; unload; echo "Stopped $LABEL. Plist kept — './service.sh start' to resume."; }

cmd_restart() {
  require_plist
  # kickstart -k kills the running copy and starts a fresh one in one step,
  # without the unload/load window where KeepAlive isn't watching.
  launchctl kickstart -k "$DOMAIN/$LABEL"
  echo "Restarted $LABEL."
}

cmd_status() {
  if [ ! -f "$PLIST" ]; then
    echo "not installed  (no $PLIST)"
    return 1
  fi
  local out
  if ! out="$(launchctl list "$LABEL" 2>/dev/null)"; then
    echo "installed, not loaded  ($PLIST)"
    echo "  ./service.sh start"
    return 1
  fi

  local pid exit_code
  pid="$(printf '%s\n' "$out" | awk '/"PID"/ {gsub(/[^0-9]/, "", $3); print $3}')"
  exit_code="$(printf '%s\n' "$out" | awk '/"LastExitStatus"/ {gsub(/[^0-9-]/, "", $3); print $3}')"

  if [ -n "$pid" ]; then
    echo "running  pid $pid"
  else
    # No PID with KeepAlive set means it is inside ThrottleInterval waiting to
    # respawn — usually Bridge not being up yet.
    echo "loaded, not running  (last exit ${exit_code:-?}; respawns within 30s)"
  fi
  [ -f "$LOG" ] && echo "log  $LOG" && tail -n 5 "$LOG" | sed 's/^/  | /'
  return 0
}

cmd_logs() {
  if [ ! -f "$LOG" ]; then
    echo "No log yet at $LOG — has it started? ./service.sh status" >&2
    exit 1
  fi
  tail -f "$LOG"
}

CONFIG_PATH=""
COMMAND="${1:-}"
[ $# -gt 0 ] && shift
while [ $# -gt 0 ]; do
  case "$1" in
    --config) CONFIG_PATH="${2:?--config needs a path}"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

case "$COMMAND" in
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  start)     cmd_start ;;
  stop)      cmd_stop ;;
  restart)   cmd_restart ;;
  status)    cmd_status ;;
  logs)      cmd_logs ;;
  *)
    usage
    exit 2 ;;
esac
